/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Model;
import controller.Util;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePrincipal.class.getName());

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        jPanelResultados.setVisible(false);
        Model.lista = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeArquivo = new javax.swing.JTextField();
        jButtonAbrir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonExecutar = new javax.swing.JButton();
        jPanelResultados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQtdNumeros = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldQtdGerar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldValMax = new javax.swing.JTextField();
        jTextFieldValMin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa e Ordenação");

        jLabel1.setText("Caminho e nome arquivo:");

        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addActionListener(this::jButtonAbrirActionPerformed);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(this::jButtonLimparActionPerformed);

        jButtonExecutar.setText("Executar");
        jButtonExecutar.addActionListener(this::jButtonExecutarActionPerformed);

        jLabel3.setText("Quantidade de Números: ");

        jTextFieldQtdNumeros.setEditable(false);
        jTextFieldQtdNumeros.setEnabled(false);
        jTextFieldQtdNumeros.addActionListener(this::jTextFieldQtdNumerosActionPerformed);

        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bolha", null, null, null},
                {"Inserção", null, null, null},
                {"Pente", null, null, null},
                {"Seleção", null, null, null},
                {"Merge", null, null, null},
                {"Quick", null, null, null}
            },
            new String [] {
                "Método", "Comparações", "Trocas", "Tempo (ms)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableResultados);

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdNumeros))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQtdNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396))
        );

        jLabel7.setText("Ou gere valores aleatórios:");

        jLabel8.setText("Qtd elementos:");

        jLabel9.setText("max val:");

        jTextFieldValMin.addActionListener(this::jTextFieldValMinActionPerformed);

        jLabel10.setText("min val:");

        jButtonGerar.setText("Gerar");
        jButtonGerar.addActionListener(this::jButtonGerarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButtonExecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldNomeArquivo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldQtdGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldValMax)
                                    .addComponent(jTextFieldValMin))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrir)
                    .addComponent(jButtonLimpar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQtdGerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldValMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButtonGerar))
                .addGap(42, 42, 42)
                .addComponent(jButtonExecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    
    /**
     * Função do botão executar
     */
    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if (Model.lista == null || Model.lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lista está vazia", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        jPanelResultados.setVisible(true);
        jTextFieldQtdNumeros.setText("" + Model.lista.size());

        // Captura o modelo de dados da tabela
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableResultados.getModel();
        modeloTabela.setRowCount(0);//limpa as linhas antigas

        String[] nomesMetodos = {"Bolha", "Inserção", "Pente", "Seleção", "Merge", "Quick"};

        
        float compSelecionado = 0, trocasSelecionado = 0, tempoSelecionado = 0;

        // Executa e popula todos os métodos na tabela comparativa
        for (int i = 0; i < 6; i++) {
            // Cria uma cópia isolada para não estragar (ordenar) a lista original do modelo
            ArrayList<Integer> listaCopia = new ArrayList<>(Model.lista);
            ArrayList<Float> metricasMetodo = new ArrayList<>();

            long tempoInicio = System.nanoTime();

            switch (i) {
                case 0: metricasMetodo.addAll(controller.Ordenacao.bolha(listaCopia)); break;
                case 1: metricasMetodo.addAll(controller.Ordenacao.insercao(listaCopia)); break;
                case 2: metricasMetodo.addAll(controller.Ordenacao.pente(listaCopia)); break;
                case 3: metricasMetodo.addAll(controller.Ordenacao.selecao(listaCopia)); break;
                case 4: metricasMetodo.addAll(controller.Ordenacao.merge(listaCopia)); break;
                case 5: metricasMetodo.addAll(controller.Ordenacao.quick(listaCopia)); break;
                default: throw new AssertionError();
            }

            long tempoFim = System.nanoTime();
            float tempoMilisegundos = (float) (tempoFim - tempoInicio) / 1000000;

            float comparacoes = metricasMetodo.get(0);
            float trocas = metricasMetodo.get(1);

            

            // O Java fará o autoboxing para Float atendendo às regras das colunas da JTable.
            modeloTabela.addRow(new Object[]{
                nomesMetodos[i], 
                comparacoes, 
                trocas, 
                tempoMilisegundos
            });
        }
    }

    
    /**
     * Executar cada separado selecionando método
    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if (Model.lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O arquivo não foi carregado para a lista", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            jPanelResultados.setVisible(true);
            switch (jComboBoxMetodos.getSelectedIndex()) {
                case 0:     //bolha
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.bolha(Model.lista));
                    tempoFim = System.nanoTime();
                    metricas.add((float) (tempoFim - tempoInicio) / 1000000);
                    break;
                case 1:     //insercao
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.insercao(Model.lista));
                    tempoFim = System.nanoTime();
                    metricas.add((float) (tempoFim - tempoInicio) / 1000000);
                    break;
                case 2:     //pente
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.pente(Model.lista));
                    tempoFim = System.nanoTime();
                    metricas.add((float) (tempoFim - tempoInicio) / 1000000);
                    break;
                case 3:     //selecao
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.selecao(Model.lista));
                    tempoFim = System.nanoTime();
                    metricas.add((float) (tempoFim - tempoInicio) / 1000000);
                    break;
                case 4:     //merge
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.merge(Model.lista));
                    tempoFim = System.nanoTime();
                    metricas.add((float) (tempoFim - tempoInicio) / 1000000);
                    break;
                case 5:     //quick
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.quick(Model.lista));
                    tempoFim = System.nanoTime();
                    metricas.add((float) (tempoFim - tempoInicio) / 1000000);
                    break;
                default:
                    throw new AssertionError();
            }
            jTextFieldQtdNumeros.setText("" + Model.lista.size());
            jTextFieldQtdComparacoes.setText("" + metricas.get(0));
            jTextFieldQtdTrocas.setText("" + metricas.get(1));
            jTextFieldTempo.setText("" + metricas.get(2));
        }
    }                                               
    **/
 
    /**
     * Função do botão Abrir (chamando função de carregar de arquivo)
     */
    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (jTextFieldNomeArquivo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Informe nome do arquivo", "Atenção", JOptionPane.ERROR_MESSAGE);
        } else {
            if (Util.carregarArquivoEmLista(jTextFieldNomeArquivo.getText(), Model.lista)) {
                JOptionPane.showMessageDialog(this, "Lista carregada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Problemas para ler o arquivo e carregar a lista", "Erro", JOptionPane.ERROR_MESSAGE);
                jTextFieldNomeArquivo.setText("");
                jTextFieldNomeArquivo.requestFocusInWindow();
            }
        }
    }                                            

    /**
     * Função do botão de limpar (set texto em branco nos campos)
     */
    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        jTextFieldNomeArquivo.setText("");
        Model.lista.clear();
        jTextFieldQtdNumeros.setText("");
        jTextFieldNomeArquivo.requestFocusInWindow();
    }                                             

    private void jTextFieldQtdNumerosActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void jTextFieldValMinActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * Função do botão gerar (chama função de gerar lista com valores aleatórios capturando valores das entradas)
     */
    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try {
        // Captura os dados digitados pelo usuário nas caixas de texto
        int quantidade = Integer.parseInt(jTextFieldQtdGerar.getText().trim());
        int minimo = Integer.parseInt(jTextFieldValMin.getText().trim());
        int maximo = Integer.parseInt(jTextFieldValMax.getText().trim());

        // Validações básicas de segurança para evitar travamentos
        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(this, "A quantidade de números deve ser maior que zero.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (minimo > maximo) {
            JOptionPane.showMessageDialog(this, "O valor mínimo não pode ser maior que o valor máximo.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Chama a função para gerar aleatorios no Util.java (Controller)
        controller.Util.gerarListaAleatoria(quantidade, minimo, maximo);

        // Limpa o painel de resultados antigo e avisa que deu certo
        jPanelResultados.setVisible(false);
        jTextFieldNomeArquivo.setText("[Lista Aleatória Gerada]");//Bloqueia para caminho de arquivo
        
        JOptionPane.showMessageDialog(this, "Lista com " + quantidade + " números gerada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        // Controle de exceção caso o usuário digite letras ou deixe campos vazios
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos de geração apenas com números inteiros válidos.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
    }
    }                                            

    /**
     * função main na view
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFramePrincipal().setVisible(true));

    }

    ArrayList<Float> metricas = new ArrayList<>();
    long tempoInicio, tempoFim;

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultados;
    private javax.swing.JTextField jTextFieldNomeArquivo;
    private javax.swing.JTextField jTextFieldQtdGerar;
    private javax.swing.JTextField jTextFieldQtdNumeros;
    private javax.swing.JTextField jTextFieldValMax;
    private javax.swing.JTextField jTextFieldValMin;
    // End of variables declaration                   
}
